---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-no-ops
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/wtrakonkun/mtl-test.git
    path: k8s-deploy-app
