apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: app.k8s.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              {{- if eq .Values.app.deployType "bluegreen" }}
              name: {{ .Values.app.name }}-bluegreen-active
              {{ else }}
              name: {{ .Values.app.name }}
              {{ end }}
              port:
                {{- if eq .Values.app.deployType "canary" }}
                name: use-annotation
                {{ else }}
                number: {{ .Values.app.service.port }}
                {{ end }}
    {{- if eq .Values.app.deployType "bluegreen" }}
    - host: app-preview.k8s.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.app.name }}-bluegreen-preview
              port:
                number: {{ .Values.app.service.port }}
    {{ end }}
                