{{- if ne .Values.app.deployType "single" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-{{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    {{- if eq .Values.app.deployType "canary" }}
    canary:
      canaryService: {{ .Values.app.name }}-canary
      stableService: {{ .Values.app.name }}-stable
      trafficRouting:
        alb:
          ingress: {{ .Values.app.name }}-ingress
          servicePort: {{ .Values.app.service.port }}
          rootService: {{ .Values.app.name }}
      steps:
      - setWeight: {{ .Values.canary.weight }}
      - pause: {}
    {{ else if eq .Values.app.deployType "bluegreen" }}
    blueGreen: 
      activeService: {{ .Values.app.name }}-bluegreen-active
      previewService: {{ .Values.app.name }}-bluegreen-preview
      autoPromotionEnabled: false
    {{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.container.image }}
        ports:
        - name: http
          containerPort: {{ .Values.app.container.port}}
          protocol: TCP
{{ end }}