app:
  name: app-no-ops
  deployType: bluegreen # single, canary, bluegreen
  replicaCount: 1
  container:
    image: beerwarin/app-no-ops:2.0
    port: 8080
  service:
    type: NodePort
    port: 80
canary:
  weight: 15